# Generated by Django 5.1.4 on 2025-01-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditPriceCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('servicii', 'Servicii'), ('producere', 'Producere'), ('comert', 'Comerț'), ('ong', 'ONG'), ('agricultura', 'Agricultură'), ('constructii', 'Construcții'), ('transport', 'Transport/Expediții')], max_length=50)),
                ('sales_volume', models.FloatField(help_text='Volumul vânzărilor (mil. lei)')),
                ('employees', models.IntegerField(help_text='Număr de salariați')),
                ('price', models.FloatField(blank=True, help_text='Preț calculat (lei)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitareServiciu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
                ('serviciu', models.CharField(max_length=200)),
                ('mesaj', models.TextField()),
                ('data_trimiterii', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
